### ISSUE TITLE
Python check will always fail on macOS with homebrew

### ISSUE THREAD

**Issue by tuemeister** [fleischr/sapbtp_dev_readiness#4]
The check for python in the script fails on macOS, if python is installed via homebrew (https://docs.brew.sh/Homebrew-and-Python), which is very common.

The script checks for ```py```, but if python is installed via homebrew, it is available with command ```python3```. Of course I can workaround this by creating a symlink.

The part of the script is this one:

```
# Check if Python is installed
python_installed=0
if command_exists py; then
    echo -e "${GREEN}Python is installed.${RESET}"
    py --version
    python_installed=1
else
    echo -e "${RED}Python is not installed.${RESET}"
fi
echo ""
```

It should also check for ```python3``` command

**Comment by fleischr** [comment]
Thanks for testing out on macOS! I've made some changes based on this and the color formatting issue.
