### ISSUE TITLE
Coloring does not work an macOS

### ISSUE THREAD

**Issue by tuemeister** [fleischr/sapbtp_dev_readiness#5]
The coloring will not work on "default" macOS with ```zsh``` preinstalled. It works when I install and run the script ```bash``` though.

Adding a shebang as the first line in the script would suffice, I suppose:

```
#!/usr/bin/env bash
```

Then, if you haven't installed ```bash``` it will fail, so you know that you need to install it.

**Comment by fleischr** [comment]
Added suggested changes. thanks!
